version: '3.8'

services:
  notifications-telegram:
    build: .
    container_name: notifications-telegram
    ports:
      - "5011:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge
